UMC-Edison/Edison-Server

project/src/main/java/com/edison/project/common/status/ErrorStatus.java
project/src/main/java/com/edison/project/domain/label/controller/LabelRestController.java
project/src/main/java/com/edison/project/domain/label/dto/LabelRequestDTO.java
project/src/main/java/com/edison/project/domain/label/entity/Label.java
project/src/main/java/com/edison/project/domain/label/service/LabelCommandService.java
project/src/main/java/com/edison/project/domain/label/service/LabelCommandServiceImpl.java
project/src/main/resources/application.properties

>close #15
1. 라벨 수정 API를 구현하였습니다.
- validation 내용은 동일, 유효하지 않은 라벨 id로 접근하는 경우에 대해서만 추가로 처리해줌
2. 라벨 삭제 API를 구현하였습니다.
- 수정 로직과 거의 90퍼 일치... 할 게 없었어요..
**_service 단에 중복코드 많은데, 전에꺼랑 충돌 일어나면 해결하기 까다로울까바 일단 이렇게 PR 날립니다! 요거 develop에 머지한 후 추가로 리팩토링 할 예정입니다,,_**
> 테스트 가능하면 테스트 해주시고, validation 빠진 부분 있는지 체크 부탁드립니다! 
그리고.. .idea 빼고 push된 거 같긴한데, 긴가민가해서 맞는지 확인해주세요 ... 
> 테스트 할 API:
> 1. PATCH, /labels/라벨아이디값
>  {
"name": "",
"color": ""
}
> 2. DELETE, /labels/라벨아이디값

✨ [FEAT] #15: 라벨 수정 및 삭제 API 작성

---

project/src/main/java/com/edison/project/domain/bubble/repository/BubbleLabelRepository.java
project/src/main/java/com/edison/project/domain/label/controller/LabelRestController.java
project/src/main/java/com/edison/project/domain/label/dto/LabelRequestDTO.java
project/src/main/java/com/edison/project/domain/label/dto/LabelResponseDTO.java
project/src/main/java/com/edison/project/domain/label/repository/LabelRepository.java
project/src/main/java/com/edison/project/domain/label/service/LabelQueryService.java
project/src/main/java/com/edison/project/domain/label/service/LabelQueryServiceImpl.java

> close #25 
> 라벨 목록 조회 API를 구현하였습니다.
- bubbleCount 조회를 위해 JPQL 사용
- 버블 없는 라벨의 bubbleCount값은 일단 null이 아니라 0으로 처리되도록 함
- validation : 유효하지 않은 memberId로 요청한 경우에 대해서만 처리함 (삭제나 수정이 아닌 조회여서, 일단 권한 관련 검증은 안했습니다)
> 아래 내용 중점으로 잘 돌아가는지 테스트 부탁드립니다!
[ GET, /labels?memberId= ]
1. 버블 없는 라벨은 count값 0으로 잘 뜨는지
2. 삭제(soft_delete)된 버블은 카운트에 추가되지 않는지
3. 복원된 버블은 카운트에 추가되는지

✨ [FEAT] #25: 라벨 목록 조회 API 작성

---

project/src/main/java/com/edison/project/domain/bubble/repository/BubbleLabelRepository.java
project/src/main/java/com/edison/project/domain/label/controller/LabelRestController.java
project/src/main/java/com/edison/project/domain/label/dto/LabelResponseDTO.java
project/src/main/java/com/edison/project/domain/label/service/LabelQueryService.java
project/src/main/java/com/edison/project/domain/label/service/LabelQueryServiceImpl.java

>close #27 
> 라벨 상세내용 조회 API를 구현하였습니다.
- 라벨에 연결된 버블 내용 조회를 위해 bubblelabelrepo에 JPQL 사용
- 서비스 단 내부에 mapping 관련 긴 코드 있는데, 버블 조회 api 구현에 따라 나중에 중복 제거할 수 있을 것 같아 일단은 냅뒀습니다!(나중에 리팩토링할게요..)
- validation 
1. 유효하지 않은 memberId로 요청한 경우
2. 유효하지 않은(=없는) labelId로 요청한 경우
3. 권한 없는 labelId(=본인이 만든게 아닌 라벨)을 요청한 경우
>1. 기능 잘 돌아가는지
>2. 위의 validation 잘 처리되는지
>3. 이외에 검증할 사항 없을지
>확인 부탁드립니다!! (쿼리나 path변수로 null들어오는 경우는 404나 500에러 떠서 일단 처리하지 않고 냅뒀어용)

✨ [FEAT] #27: 라벨 상세 조회 API 작성

---

project/src/main/java/com/edison/project/common/response/ApiResponse.java
project/src/main/java/com/edison/project/common/response/PageInfo.java
project/src/main/java/com/edison/project/domain/bubble/controller/BubbleRestController.java
project/src/main/java/com/edison/project/domain/bubble/dto/BubbleRequestDto.java
project/src/main/java/com/edison/project/domain/bubble/dto/BubbleResponseDto.java
project/src/main/java/com/edison/project/domain/bubble/repository/BubbleRepository.java
project/src/main/java/com/edison/project/domain/bubble/service/BubbleService.java
project/src/main/java/com/edison/project/domain/bubble/service/BubbleServiceImpl.java
project/src/main/java/com/edison/project/domain/label/dto/LabelResponseDTO.java
project/src/main/java/com/edison/project/domain/label/service/LabelQueryServiceImpl.java

> close #32 
> 스페이스에서 전체 버블 목록을 조회하는 API를 구현하였습니다.
- 유저 검증
- 페이지네이션 적용, size = 20
- 최신순 정렬
- 성공 시
- 존재하지 않는 유저인 경우

✨[FEAT] #32: 전체 버블 목록 조회 구현

---

project/src/main/java/com/edison/project/common/status/ErrorStatus.java
project/src/main/java/com/edison/project/domain/label/dto/LabelRequestDTO.java
project/src/main/java/com/edison/project/domain/label/dto/LabelResponseDTO.java
project/src/main/java/com/edison/project/domain/label/entity/Label.java
project/src/main/java/com/edison/project/domain/label/service/LabelCommandServiceImpl.java
project/src/main/java/com/edison/project/domain/label/service/LabelQueryServiceImpl.java

>close #34 
> 라벨 색상 타입 enum string에서, int로 변경하였습니다(0이상, 10자리 이하의 정수값으로 들어오도록)
> 들어오는 값 type검증은 일단 안했습니다!(다른 api들도 다 안된 것 같아서, 상위 exception 패키지에서 처리하는 게 나을 것 같아요)
>라벨 색상 int 아닌 타입으로 했을 시, 500에러 뜨는 거 확인해주세요! 
>(라벨 생성, POST) /labels

🐛 [HOTFIX] #34 라벨 색상 타입 int로 변경

---

project/src/main/java/com/edison/project/ProjectApplication.java
project/src/main/java/com/edison/project/domain/bubble/controller/BubbleRestController.java
project/src/main/java/com/edison/project/domain/bubble/dto/BubbleResponseDto.java
project/src/main/java/com/edison/project/domain/bubble/entity/Bubble.java
project/src/main/java/com/edison/project/domain/bubble/service/BubbleService.java
project/src/main/java/com/edison/project/domain/bubble/service/BubbleServiceImpl.java
project/src/main/java/com/edison/project/domain/label/service/LabelQueryServiceImpl.java
project/src/main/resources/application.properties

> close #24 
- updatedAt 시간 동기화가 잘 안되어서 EntityManager flush 하고 출력하는 방식으로 구현했습니다.
- 버블 클래스에서 겹치는 코드가 너무 많아서 `convertToBubbleResponseDto(Bubble bubble)` 공통함수 생성하였습니다.
> 관련 로직 중 제가 수정하지 못한 api가 있다면 알려주십셔 !

✨[FEAT] #11: 버블 수정 기능 구현 및 버블 출력 dto 형식 수정

---

project/src/main/java/com/edison/project/domain/member/controller/MemberRestController.java
project/src/main/java/com/edison/project/domain/member/repository/MemberRepository.java
project/src/main/java/com/edison/project/domain/member/service/MemberService.java
project/src/main/java/com/edison/project/domain/member/service/MemberServiceImpl.java
project/src/main/java/com/edison/project/global/security/JwtAuthenticationFilter.java
project/src/main/resources/application.properties

> ex) close #57 
> 회원 탈퇴하는 API입니다.
- 탈퇴 성공
- 탈퇴 후 다른 api 요청

✨ [FEAT] #57 계정 탈퇴 API 

---

.idea/.gitignore
project/src/main/java/com/edison/project/domain/bubble/controller/BubbleRestController.java
project/src/main/java/com/edison/project/domain/bubble/dto/BubbleRequestDto.java
project/src/main/java/com/edison/project/domain/bubble/dto/BubbleResponseDto.java
project/src/main/java/com/edison/project/domain/bubble/entity/Bubble.java
project/src/main/java/com/edison/project/domain/bubble/service/BubbleService.java
project/src/main/java/com/edison/project/domain/bubble/service/BubbleServiceImpl.java
project/src/main/java/com/edison/project/global/common/entity/BaseEntity.java

.## #⃣ 연관된 이슈
> close #98 
- 로컬 DB에서 버블 생성, 수정, 삭제(soft-delete)가 이루어진 데이터들을 받아와서 서버 DB에서 SYNC 맞춰 저장하는 기능입니다.
- 서버 DB에 해당 버블 ID가 없는 경우 -> 생성
- 서버 DB에 해당 버블 ID가 있는 경우 -> 수정
- 위 두 경우에서 isDeleted가 true인 경우, soft-delete가 동시 발생(=수정)
- createdAt, updatedAt이 BaseEntity 설정으로 입력값에 상관없이 DB에 생성된(수정된) 시간으로 덮어씌워지는 경우가 발생하여, Bubble 엔티티의 경우 BaseEntity extends가 아닌, 버블 엔티티 내 일반 컬럼으로 수정하여 해결하였습니다.
- 세 경우가 모두 잘 작동하는지, createdAt, updatedAt이 DB 상에서도 입력값으로 잘 저장이 되는 지 확인 부탁드려용

✨[FEAT] #98: 버블 SYNC 기능 구현

---

project/src/main/java/com/edison/project/common/status/ErrorStatus.java
project/src/main/java/com/edison/project/domain/member/controller/MemberRestController.java
project/src/main/java/com/edison/project/domain/member/dto/MemberRequestDto.java
project/src/main/java/com/edison/project/domain/member/service/MemberServiceImpl.java
project/src/main/java/com/edison/project/global/security/JwtAuthenticationFilter.java
project/src/main/resources/application.properties

> ex) close #83 
> access토큰 재발급 받을 때 헤더에 access토큰과 refresh토큰 둘다 요청하는 방법으로 바꿨습니다! 현재 배포된 서버에는 다른 application.properties가 적용되고 있어서 로컬서버에서 진행해야합니다! 만료된 토큰으로 재발급 테스트 할 때는 환경변수 JWT_ACCESS_EXPIRATION,  JWT_REFRESH_EXPIRATION이 값을 바꾸고 확인해주세요!
- 재발급 성공(access토큰 만료, refresh토큰 유효)
- access 토큰 유효할 때 재발급
- access토큰, refresh토큰 모두 만료
- 로그아웃하고 재발급 한 경우
- access 토큰 만료되었을 때 다른 api 요청
>

🐛 [!HOTFIX] #83 refresh토큰으로 access토큰 재발급

---

project/src/main/java/com/edison/project/common/status/ErrorStatus.java
project/src/main/java/com/edison/project/domain/bubble/controller/BubbleRestController.java
project/src/main/java/com/edison/project/domain/bubble/dto/BubbleRequestDto.java
project/src/main/java/com/edison/project/domain/bubble/dto/BubbleResponseDto.java
project/src/main/java/com/edison/project/domain/bubble/entity/Bubble.java
project/src/main/java/com/edison/project/domain/bubble/repository/BubbleLabelRepository.java
project/src/main/java/com/edison/project/domain/bubble/repository/BubbleRepository.java
project/src/main/java/com/edison/project/domain/bubble/service/BubbleService.java
project/src/main/java/com/edison/project/domain/bubble/service/BubbleServiceImpl.java
project/src/main/java/com/edison/project/domain/label/repository/LabelRepository.java
project/src/main/java/com/edison/project/domain/member/service/MemberServiceImpl.java

> close #104 
- 서버 DB에 해당 버블 ID가 없는 경우 -> 생성
- 서버 DB에 해당 버블 ID가 있는 경우 -> 수정
- 위 두 경우에서 isTrashed가 true인 경우, soft-delete가 동시 발생(=수정)
- isDeleted가 true인 경우 → 삭제 ✔️ 요부분까지 작동하도록 업데이트
- 엔티티 수정 (trashed - softdelete, deleted - harddelete)
- 새로운 버블 & isDeleted = false -> 생성
- 존재하는 버블 & isDeleted = false -> 수정
- 새로운 버블 & isDeleted = true -> db에 저장 안 하고 바로 결과 반환
- 존재하는 버블 & isDeleted = true -> 삭제
> 서버 디비에 없는 아이디가 isDeleted = true인 상태로 넘어왔을 때(로컬에서 생성->harddelete까지 된 후 넘어온 상태), db에는 아예 안 저장되고 결과 반환 아래와 같이 잘 되는 지 확인해주세용

❕[!HOTFIX] #104: 버블 SYNC HardDelete 추가 구현

---

project/src/main/java/com/edison/project/domain/member/controller/MemberRestController.java
project/src/main/java/com/edison/project/domain/member/dto/MemberResponseDto.java
project/src/main/java/com/edison/project/domain/member/service/MemberService.java
project/src/main/java/com/edison/project/domain/member/service/MemberServiceImpl.java

> ex) close #103 
> 마이페이지창에 보이는 회원 정보(닉네임, 이메일, 프로필사진)를 가져오는 API입니다.
>

✨[FEAT] #103 프로필 회원 정보 조회 API

---

project/src/main/java/com/edison/project/domain/label/service/LabelQueryServiceImpl.java

>close #105 
>라벨 sync api의 삭제 로직에서, id와 isDeleted 필드의 값을 제외한 다른 필드의 값들도 null이 아니라 정상적으로 출력되도록 수정하였습니다.
- 수정 후
> localhost:8080/labels/sync(혹은 서버주소) 에서, isDeleted=true로 라벨 삭제 진행 시, name/color/시간 필드들의 값이 null이 아니라 요청값 그대로 잘 출력되는지만 확인해주세요!

❕ [!HOTFIX] #105 라벨 SYNC 삭제 로직 응답DTO 수정

---

project/src/main/java/com/edison/project/common/exception/ExceptionAdvice.java
project/src/main/java/com/edison/project/common/status/ErrorStatus.java
project/src/main/java/com/edison/project/domain/artletter/controller/ArtletterController.java
project/src/main/java/com/edison/project/domain/artletter/dto/ArtletterDTO.java
project/src/main/java/com/edison/project/domain/artletter/service/ArtletterService.java
project/src/main/java/com/edison/project/domain/artletter/service/ArtletterServiceImpl.java
project/src/main/java/com/edison/project/domain/scrap/repository/ScrapRepository.java

> ex) close #113 
> 카테고리별 스크랩 아트레터 조회 api(회원이 스크랩한 모든 아트레터들을 조회하는데 같은 카테고리들은 묶여서 나옵니다!)
& 카테고리에 해당하는 스크랩 아트레터 조회 api(해당하는 카테고리의 아트레터들)를 구현했습니다! 
- 스크랩한 전체 아트레터 조회
- 스크랩한 아트레터 중 해당하는 카테고리의 아트레터 조회
- 존재하지 않는 카테고리로 요청한 경우
>

feat: 카테고리별 스크랩한 아트레터 조회 및 카테고리에 해당하는 스크랩 아트레터 조회 api

---

project/src/main/java/com/edison/project/common/status/ErrorStatus.java
project/src/main/java/com/edison/project/global/security/CustomAuthenticationEntryPoint.java
project/src/main/java/com/edison/project/global/security/JwtAuthenticationFilter.java

> ex) close #116 
> 헤더에 토큰이 없거나 Bearer 형식이 맞지 않는 경우 커스텀 엔트리 페이지로 넘어가서 에러처리
-> JwtAuthenticationFilter에서 예외가 터지는 방식으로 바꿨습니다! 
>
> 이제 api에서 토큰이 없으면 위의 사진과 같은 에러가 나는지 확인해주시면 감사하겠습니다~!

❕[!HOTFIX] #116:  필터에 토큰 없을 경우 예외처리추가

---

project/build.gradle
project/src/main/java/com/edison/project/domain/member/controller/MemberRestController.java
project/src/main/java/com/edison/project/domain/member/dto/MemberRequestDto.java
project/src/main/java/com/edison/project/domain/member/dto/MemberResponseDto.java
project/src/main/java/com/edison/project/domain/member/entity/Member.java
project/src/main/java/com/edison/project/domain/member/service/MemberService.java
project/src/main/java/com/edison/project/domain/member/service/MemberServiceImpl.java
project/src/main/java/com/edison/project/global/config/AppConfig.java
project/src/main/java/com/edison/project/global/config/SecurityConfig.java
project/src/main/java/com/edison/project/global/util/JwtUtil.java

> close #114 
> 현재 회원가입/로그인 방식을 변경하였습니다!
-> 프론트에서 구글로그인 요청하고 발급받은 idToken을 통해 에디슨 토큰을 발급합니다!
> 이제 회원가입/로그인(에디슨 서비스 토큰을 발급)을 프론트가 보내준 idToken으로 하기 때문에 환경변수인 GOOGLE_CLIENT를 프론트에서 받은 값으로 바꿔줘야 합니다! 에디슨 전체톡방에 있으니 참고해주세요! 그런데 이렇게 바꾸고 나면 웹에서 발급받은 토큰을 사용하지 못하기 때문에 환경변수 값을 바꾸지 말고 JwtUtil파일의 CLIENT_ID값을 바꿔주세요!  <img width="717" alt="스크린샷 2025-02-10 오후 3 11 26" src="https://github.com/user-attachments/assets/185fb869-9e1f-46a1-bf4e-d4ba2e9e1771" />
> 지금 테스트는 프론트에서 발급받은 idToken을 사용하여 나온 accessToken으로 다른 api가 되는지 확인해주세요!
> 정리) 프론트에서 로그인을 하려면 id토큰을 사용하여 members/google api에서 토큰 발급받아야함. 백에서는 기존 방식으로 웹에서 발급받은 access토큰을 사용하여 api테스트 할 수 있도록 해둠.

❕[!HOTFIX] #114: 구글로그인 토큰발급 방식 변경

---

project/src/main/java/com/edison/project/global/HealthCheckController.java
project/src/main/java/com/edison/project/global/config/SecurityConfig.java

- close #119 
이전 SecurityConfig.java를 보면, 모든 요청이 인증을 필요로 합니다.
/ 같은 경로를 ELB에서 헬스 체크하려 해도, Spring Security가 인증을 요구하고 있기 때문에 401 Unauthorized가 발생합니다.
ELB는 기본적으로 로그인할 수 없으므로, Health Check 엔드포인트(/health 같은 경로)에 대해 인증을 제외해야 합니다.
>

🐛[BUG] #119 health check 컨트롤러 추가, 인증 permit

---

project/src/main/java/com/edison/project/domain/artletter/repository/ArtletterRepositoryCustomImpl.java
project/src/main/java/com/edison/project/domain/artletter/service/ArtletterServiceImpl.java

> close #124 
전반적으로 method extracting 진행하도록, 아래 3가지 api 리팩토링 하였습니다.
**1. 아트레터 컨텐츠 페이지 조회 QA**
> - **code refactor**
> - [x] repo : 크게 search/count/pagination 로 나누어져 있었던 전체 로직을 함수로 분리함
> - [x] service : 공통적으로 쓰이는 letter, member 검증 로직을 분리 + 결과 반환함수도 분리
> - **validation logic - 수정사항 없음**
**2. 아트레터 스크랩 토글 QA**
> - **code refactor**
> - [x] service : 스크랩 토글 로직, 결과 생성 메서드를 별도 메서드로 분리함
> - **validation logic**
> - [x] 여러 사용자의 동시접근 고려하여 Transactional 설정
**3. 아트레터 좋아요 토글 QA**
> - 전체적으로 스크랩 토글과 유사하게 리팩토링
> 코드 정상적으로 잘 돌아가는지 확인하고, 코드리뷰 부탁드려요~~

🛠️ [REFACTOR] #124 아트레터 관련 QA

---

project/src/main/java/com/edison/project/domain/artletter/controller/ArtletterController.java
project/src/main/java/com/edison/project/domain/artletter/service/ArtletterServiceImpl.java
project/src/main/java/com/edison/project/domain/member/controller/MemberRestController.java
project/src/main/java/com/edison/project/domain/member/service/MemberService.java
project/src/main/java/com/edison/project/domain/member/service/MemberServiceImpl.java
project/src/main/java/com/edison/project/global/config/SecurityConfig.java
project/src/main/java/com/edison/project/global/security/JwtAuthenticationFilter.java

> ex) close #129 
> 아트레터 등록, 스크랩/좋아요, 스크랩 아트레터 조회 api를 제외한 아트보트api들은 로그인 없이 접근 가능하게 수정했습니다!
> accessToken 재발급이 안 되는 문제도 수정했습니다!(members/refresh api)
>
> 아트보드 api요청이 되는지 확인해주세용
>토큰 재발급도 확인해주시면 감사하겠습니당

❕ [!HOTFIX] #129 아트보드 접근, accessToken재발급 수정

---

project/src/main/java/com/edison/project/domain/member/dto/MemberResponseDto.java
project/src/main/java/com/edison/project/domain/member/service/MemberServiceImpl.java

> ex) close #139 
> 회원가입/로그인 응답dto 수정하였습니다!
> isNewUser: true (회원가입), false (로그인)
>

❕ [!HOTFIX] #139 회원가입/로그인 응답dto 수정

---

project/src/main/java/com/edison/project/domain/bubble/dto/BubbleRequestDto.java
project/src/main/java/com/edison/project/domain/bubble/entity/Bubble.java
project/src/main/java/com/edison/project/domain/bubble/service/BubbleServiceImpl.java
project/src/main/java/com/edison/project/domain/label/controller/LabelRestController.java
project/src/main/java/com/edison/project/domain/label/dto/LabelRequestDTO.java
project/src/main/java/com/edison/project/domain/label/dto/LabelResponseDTO.java
project/src/main/java/com/edison/project/domain/label/entity/Label.java
project/src/main/java/com/edison/project/domain/label/repository/LabelRepository.java
project/src/main/java/com/edison/project/domain/label/service/LabelQueryServiceImpl.java

> close #143 
전체 아트레터 조회 QA, 아트레터 검색 QA, 아트레터 정렬 추가구현 진행함.
**라벨**
> - logic
>     - SYNC, 조회 등 모든 API에서 서버 DB의 id 값이 아닌 서버 DB의 local_idx 값(즉 사용자 로컬 DB의 pk 값)을 사용하도록 수정
>     - 라벨을 조회할 때 member와 local_idx 값으로 찾으므로 권한 검증 로직 삭제
**버블**
> - logic
>     - 라벨과 동일하게 request로는 localIdx를 받아옴
>     - 내부 로직에서는 localIdx -> label Id 값으로 변환하여 수행
>     - response에는 다시 localIdx 로 변환한 리스트로 반환
수정된 API
- 라벨 SYNC
- 라벨 목록 조회
- 라벨 상세 조회
- 버블 SYNC
- 버블 검색
- 버블 리스트 조회 (전체, 7일 이내, 상세정보)
> 수정된 API 가 모두 잘 돌아가는 지, localIdx값으로 잘 작동하고 저장되는 지 확인해주세요

❕[!HOTFIX] #143: 라벨 local_idx 관련 로직 전면 수정

---

project/src/main/java/com/edison/project/common/status/ErrorStatus.java
project/src/main/java/com/edison/project/domain/member/controller/MemberRestController.java
project/src/main/java/com/edison/project/domain/member/dto/MemberRequestDto.java
project/src/main/java/com/edison/project/domain/member/dto/MemberResponseDto.java
project/src/main/java/com/edison/project/domain/member/entity/Member.java
project/src/main/java/com/edison/project/domain/member/service/MemberService.java
project/src/main/java/com/edison/project/domain/member/service/MemberServiceImpl.java

>close #141 
> 개인정보 관련 3개 api QA 진행하였습니다.
> 1. 개인정보(닉네임) 설정
> 2. 개인정보 변경
> 3. 개인정보 조회
- code refactor
- logic
> 기능변화 없는 코드 리팩터링 & 불필요한 검증 로직 제거 위주로 QA 해서 크게 바뀐 건 없습니다
>
> 기존의 2.개인정보 변경 api 에서는, 
닉네임을 20자 이상으로 수정 가능했어서 요거 고쳤는데 
이부분만 테스트 해주세요!

🛠️ [REFACTOR] #141 개인정보 관련 QA

---

project/src/main/java/com/edison/project/domain/bubble/controller/BubbleRestController.java
project/src/main/java/com/edison/project/domain/bubble/dto/BubbleRequestDto.java
project/src/main/java/com/edison/project/domain/bubble/dto/BubbleResponseDto.java
project/src/main/java/com/edison/project/domain/bubble/entity/Bubble.java
project/src/main/java/com/edison/project/domain/bubble/repository/BubbleRepository.java
project/src/main/java/com/edison/project/domain/bubble/service/BubbleService.java
project/src/main/java/com/edison/project/domain/bubble/service/BubbleServiceImpl.java
project/src/main/java/com/edison/project/domain/label/entity/Label.java
project/src/main/java/com/edison/project/domain/label/service/LabelQueryServiceImpl.java

> close #146 
**버블 로직 수정**
> - logic
>     - SYNC, 조회 등 모든 API에서 서버 DB의 id 값이 아닌 서버 DB의 local_idx 값(즉 사용자 로컬 DB의 pk 값)을 사용하도록 수정
>     - 버블을 조회할 때 member와 local_idx 값으로 찾으므로 권한 검증 로직 삭제
**QA**
> 중복되는 코드 분리
수정된 API
- 버블 SYNC
- 버블 검색
- 버블 리스트 조회 (전체, 7일 이내, 상세정보)
> 수정된 API 가 모두 잘 돌아가는 지, localIdx값으로 잘 작동하고 저장되는 지 확인해주세요

❕[!HOTFIX] #146: 버블 local_idx 관련 로직 전면 수정

---

project/src/main/java/com/edison/project/domain/bubble/repository/BubbleRepository.java
project/src/main/java/com/edison/project/domain/bubble/service/BubbleServiceImpl.java

> close #160 
> 버블 조회 api 휴지통에 있는 애들도 조회되도록 수정했습니다.
>

❕ [!HOTFIX] #160 전체(휴지통포함으로) 버블 조회 api 수정

---

project/src/main/java/com/edison/project/common/exception/ExceptionAdvice.java
project/src/main/java/com/edison/project/common/status/ErrorStatus.java
project/src/main/java/com/edison/project/domain/artletter/controller/ArtletterController.java
project/src/main/java/com/edison/project/domain/artletter/dto/ArtletterDTO.java
project/src/main/java/com/edison/project/domain/artletter/service/ArtletterService.java
project/src/main/java/com/edison/project/domain/artletter/service/ArtletterServiceImpl.java
project/src/main/java/com/edison/project/domain/member/entity/Member.java
project/src/main/java/com/edison/project/domain/member/entity/MemberMemory.java
project/src/main/java/com/edison/project/domain/member/repository/MemberMemoryRepository.java
project/src/main/java/com/edison/project/domain/member/repository/MemberRepository.java
project/src/main/java/com/edison/project/global/security/JwtAuthenticationFilter.java

>close #165 
> 아트레터 - 최근검색어 저장/조회/삭제 로직을 구현하였습니다.
> 최근 검색어 저장은 아트레터 검색 시 저장됩니다!
> 최근 검색어 로직은 로그인이 필요합니다
**현재 코드가 쫌 더러운데, 코드 불 필요한 부분 있으면 그냥 브랜치 들어가서 바로 지워주시면 감사하겟습니다,,,,,,ㅠㅜ**
> 1. 검색 시 검색어 저장 잘 되는지(최근 3개까지)
> 2. 검색 조회 잘 되는지(최근 검색어를 먼저 반환하도록 함)
> 3. 검색 삭제 잘 되는지(db에서도 잘 삭제되는지)
> 4. 이외의 필요한 검증 사항,,,
조회 : get, localhost:8080/artletters/search-memory
삭제 : delete, localhost:8080/artletters/search-memory
(삭제 request body: 
{
"keyword": "문학"
})

✨ [FEAT] #165 아트레터 - 최근검색어 로직 구현

---

project/src/main/java/com/edison/project/domain/artletter/controller/ArtletterController.java
project/src/main/java/com/edison/project/domain/artletter/service/ArtletterService.java
project/src/main/java/com/edison/project/domain/artletter/service/ArtletterServiceImpl.java

> close #170 
> 아트레터 최근 검색어 삭제 api의 request를 body값이 아니라 query parmas로 받도록 수정하였습니다.
> localhost:8080/artletters/search-memory?keyword=기술과학

❕ [HOTFIX] #170 아트레터 최근 검색어 삭제 query params로 수정

---

project/src/main/java/com/edison/project/domain/artletter/service/ArtletterServiceImpl.java

> 아트레터 관련 api 로그인 안 했을 때 생기는 에러 수정했습니다!
> 아트레터 조회, 검색 로그인없이 되는지 확인해주세요!

❕ [HOTFIX] #170 아트레터 검색, 조회 api 로그인 없을 때 에러 수정

---

project/src/main/java/com/edison/project/domain/artletter/controller/ArtletterController.java
project/src/main/java/com/edison/project/domain/artletter/dto/ArtletterDTO.java
project/src/main/java/com/edison/project/domain/artletter/repository/ArtletterRepository.java
project/src/main/java/com/edison/project/domain/artletter/service/ArtletterService.java
project/src/main/java/com/edison/project/domain/artletter/service/ArtletterServiceImpl.java
project/src/main/java/com/edison/project/domain/scrap/repository/ScrapRepository.java

> ex) #169 
아트레터 카테고리별로 조회하는 api 설계하였습니다.
> 로그인 되지 않았을 시 scraped = false 나오고, 로그인되었을땐 잘 나오는지 확인해주세요!

✨ [FEAT] #169 : 아트레터 카테고리별 조회 API 설계, close #169

---

project/src/main/java/com/edison/project/domain/bubble/entity/BubbleBacklink.java
project/src/main/java/com/edison/project/domain/bubble/repository/BubbleBacklinkRepository.java
project/src/main/java/com/edison/project/domain/bubble/service/BubbleServiceImpl.java

> ex) close #177 
> 버블 sync에서 soft delete, hard delete시 관련된 백링크 엔티티도 soft, hard delete되게 리팩토링했습니다.
>
> 백링크가 걸린 버블을 삭제했을 때, 백링크를 걸은 버블을 삭제했을 때 관련 백링크 엔티티가 제대로 삭제되는지 확인해주세요!(soft, hard 둘 다!!)

[REFACTOR] #176: 버블 삭제(soft,hard)시 관련 백링크엔티티도 삭제(soft,hard)

---

project/src/main/java/com/edison/project/domain/artletter/controller/ArtletterController.java
project/src/main/java/com/edison/project/domain/artletter/repository/ArtletterRepository.java
project/src/main/java/com/edison/project/domain/artletter/service/ArtletterService.java
project/src/main/java/com/edison/project/domain/artletter/service/ArtletterServiceImpl.java
project/src/main/java/com/edison/project/domain/scrap/repository/ScrapRepository.java
project/src/main/java/com/edison/project/global/config/SecurityConfig.java

> #216
> 아트레터 읽고 나서 하단에 현재 아트레터를 제외한 다른 아트레터를 랜덤으로 3개 띄워주는 api를 설계했습니다.
>

[FEAT] #216: 현재 아트레터 제외 랜덤 추천 API 설계, closes #216

---

project/src/main/java/com/edison/project/domain/artletter/dto/ArtletterDTO.java
project/src/main/java/com/edison/project/domain/artletter/entity/Artletter.java
project/src/main/java/com/edison/project/domain/artletter/entity/Writer.java
project/src/main/java/com/edison/project/domain/artletter/repository/WriterRepository.java
project/src/main/java/com/edison/project/domain/artletter/service/ArtletterServiceImpl.java

> #231 
> 아트레터 상세조회시 작가 정보 반환하도록 했습니다. DTO 따로 만들어놨습니다....!! DB도 수정햇어욤
>

🚧 [REFACTOR] #231 아트레터 조회시 작가 정보도 같이 반환되도록 수정
