UMC-Edison/Edison-Server

- project/src/main/java/com/edison/project/ProjectApplication.java
- project/src/main/java/com/edison/project/domain/artletter/entity/Artletter.java
- project/src/main/java/com/edison/project/domain/artletter/entity/ArtletterLikes.java
- project/src/main/java/com/edison/project/domain/artletter/repository/ArtletterRepository.java
- project/src/main/java/com/edison/project/domain/board/entity/Board.java
- project/src/main/java/com/edison/project/domain/boardartletter/entity/BoardArtletter.java
- project/src/main/java/com/edison/project/domain/bubble/entity/Bubble.java
- project/src/main/java/com/edison/project/domain/bubble/entity/BubbleLabel.java
- project/src/main/java/com/edison/project/domain/bubble/repository/BubbleRepository.java
- project/src/main/java/com/edison/project/domain/images/entity/Images.java
- project/src/main/java/com/edison/project/domain/keywords/entity/Keywords.java
- project/src/main/java/com/edison/project/domain/label/entity/Label.java
- project/src/main/java/com/edison/project/domain/label/repository/LabelRepository.java
- project/src/main/java/com/edison/project/domain/member/entity/Member.java
- project/src/main/java/com/edison/project/domain/member/entity/MemberKeyword.java
- project/src/main/java/com/edison/project/domain/member/repository/MemberRepository.java
- project/src/main/java/com/edison/project/domain/scrap/entity/Scrap.java
- project/src/main/java/com/edison/project/global/common/entity/BaseEntity.java
- project/src/main/resources/application.properties
> ex) #2
> 엔티티 설계 했습니다.. ..
> https://www.notion.so/ea0a305d36b546609def39b91dc21716 !!
> 더 필요하거나 빼먹은 부분 있다면 확인 한번만 부탁드립니다!
> ✨[FEAT] #2: 엔티티 초기 설계

- project/src/main/java/com/edison/project/domain/artletter/entity/Artletter.java
- project/src/main/java/com/edison/project/domain/artletter/entity/ArtletterLikes.java
- project/src/main/java/com/edison/project/domain/artletter/repository/ArtletterRepository.java
- project/src/main/java/com/edison/project/domain/board/entity/Board.java
- project/src/main/java/com/edison/project/domain/boardartletter/entity/BoardArtletter.java
- project/src/main/java/com/edison/project/domain/bubble/entity/Bubble.java
- project/src/main/java/com/edison/project/domain/bubble/entity/BubbleLabel.java
- project/src/main/java/com/edison/project/domain/bubble/repository/BubbleRepository.java
- project/src/main/java/com/edison/project/domain/images/entity/Images.java
- project/src/main/java/com/edison/project/domain/keywords/entity/Keywords.java
- project/src/main/java/com/edison/project/domain/label/entity/Label.java
- project/src/main/java/com/edison/project/domain/label/repository/LabelRepository.java
- project/src/main/java/com/edison/project/domain/member/entity/Member.java
- project/src/main/java/com/edison/project/domain/member/entity/MemberKeyword.java
- project/src/main/java/com/edison/project/domain/member/repository/MemberRepository.java
- project/src/main/java/com/edison/project/domain/scrap/entity/Scrap.java
- project/src/main/java/com/edison/project/global/common/entity/BaseEntity.java
> ex) #2
> 바보처럼 edison이 아닌 example로 되어있는 코드들 있어서 수정했습니다 ㅠㅠ..
> fix #6: 프로젝트명 에디슨으로 통일

- project/src/main/java/com/edison/project/ProjectApplication.java
- project/src/main/java/com/edison/project/domain/artletter/entity/Artletter.java
- project/src/main/java/com/edison/project/domain/artletter/entity/ArtletterLikes.java
> 오탈자 수정했습니다 ㅠㅠ!!! 제 컴퓨터에서는 제대로 작동하나 아니면 말씀 부탁드립니다. :)
> 🔨  [FIX] #2 오타 수정 example -> edison

- project/build.gradle
- project/src/main/java/com/edison/project/common/status/ErrorStatus.java
- project/src/main/java/com/edison/project/domain/bubble/controller/BubbleRestController.java
- project/src/main/java/com/edison/project/domain/bubble/dto/BubbleRequestDto.java
- project/src/main/java/com/edison/project/domain/bubble/dto/BubbleResponseDto.java
- project/src/main/java/com/edison/project/domain/bubble/entity/Bubble.java
- project/src/main/java/com/edison/project/domain/bubble/entity/BubbleLabel.java
- project/src/main/java/com/edison/project/domain/bubble/repository/BubbleLabelRepository.java
- project/src/main/java/com/edison/project/domain/bubble/repository/BubbleRepository.java
- project/src/main/java/com/edison/project/domain/bubble/service/BubbleService.java
- project/src/main/java/com/edison/project/domain/bubble/service/BubbleServiceImpl.java
- project/src/main/resources/application.properties
> close #10 
1. bubble 관련 엔티티를 builder 패턴으로 수정하였습니다.
2. 라벨 Id가 Integer로 되어있는 부분들을 Long으로 수정하였습니다.
3. 버블을 생성하기 전 관련 검증들을 거치도록 구현하였습니다.
- MemberId가 유효한 값인 지
- linkedBubbleId의 bubbleId 값이 유효한 값인 지
- 라벨 개수가 3개 이하인 지
- 붙이려는 라벨이 유효한 지
>
> ✨[FEAT] #4: 버블 생성 API 구현

- project/build.gradle
- project/src/main/java/com/edison/project/common/status/ErrorStatus.java
- project/src/main/java/com/edison/project/domain/bubble/controller/BubbleRestController.java
- project/src/main/java/com/edison/project/domain/bubble/dto/BubbleRequestDto.java
- project/src/main/java/com/edison/project/domain/bubble/dto/BubbleResponseDto.java
- project/src/main/java/com/edison/project/domain/bubble/entity/Bubble.java
- project/src/main/java/com/edison/project/domain/bubble/entity/BubbleLabel.java
- project/src/main/java/com/edison/project/domain/bubble/repository/BubbleLabelRepository.java
- project/src/main/java/com/edison/project/domain/bubble/repository/BubbleRepository.java
- project/src/main/java/com/edison/project/domain/bubble/service/BubbleService.java
- project/src/main/java/com/edison/project/domain/bubble/service/BubbleServiceImpl.java
- project/src/main/resources/application.properties
> close #18 
> 버블을 삭제하는 API
1. 해당 버블 Id의 삭제되지 않은 버블이 있는 지 조회합니다.
2. 버블의 소유자와 요청자가 같은 지 검증합니다.
3. bubble의 is_deleted 값을 false -> true 로 변경합니다.
> 휴지통에 있는 버블을 복원하는 API
1. 해당 버블 Id의 삭제된 버블이 있는 지(휴지통에 존재하는 지) 조회합니다.
2. 버블의 소유자와 요청자가 같은 지 검증합니다.
3. bubble의 is_deleted 값을 true -> false 로 변경합니다.
- 공통 로직
- 성공 시
- 해당 버블이 존재하지 않는 경우
- 유저 권한이 없을 때
> 아직 버블 생성 API가 develop 브랜치에 머지전이라 이 브랜치에 머지한 후에 작업하여서, 관련 내용은 빼고 보셔도 됩니당..!!
> ✨[FEAT] #7: 버블 삭제, 버블 복원 API 구현

- project/src/main/java/com/edison/project/common/status/ErrorStatus.java
- project/src/main/java/com/edison/project/domain/bubble/controller/BubbleRestController.java
- project/src/main/java/com/edison/project/domain/bubble/dto/BubbleRequestDto.java
- project/src/main/java/com/edison/project/domain/bubble/service/BubbleService.java
- project/src/main/java/com/edison/project/domain/bubble/service/BubbleServiceImpl.java
- project/src/main/java/com/edison/project/domain/label/controller/LabelRestController.java
- project/src/main/java/com/edison/project/domain/label/dto/LabelRequestDTO.java
- project/src/main/java/com/edison/project/domain/label/service/LabelCommandService.java
- project/src/main/java/com/edison/project/domain/label/service/LabelCommandServiceImpl.java
- project/src/main/java/com/edison/project/domain/label/service/LabelQueryService.java
- project/src/main/java/com/edison/project/domain/label/service/LabelQueryServiceImpl.java
- project/src/main/java/com/edison/project/global/config/SecurityConfig.java
- project/src/main/java/com/edison/project/global/security/CustomUserPrincipal.java
- project/src/main/java/com/edison/project/global/security/JwtAuthenticationFilter.java
- project/src/main/java/com/edison/project/global/util/JwtUtil.java
> #10, #12 , #15 , #18 , #24, #25, #27, #32, close #33 
> memberId를 직접 넘겨주는 방식이 아닌 토큰에서 불러오는 형식으로 다 수정했습니다!
> 🐛 [HOTFIX] #33: api 토큰처리 수정

- project/src/main/java/com/edison/project/common/status/ErrorStatus.java
- project/src/main/java/com/edison/project/domain/bubble/controller/BubbleRestController.java
- project/src/main/java/com/edison/project/domain/bubble/dto/BubbleRequestDto.java
- project/src/main/java/com/edison/project/domain/bubble/repository/BubbleRepository.java
- project/src/main/java/com/edison/project/domain/bubble/service/BubbleService.java
- project/src/main/java/com/edison/project/domain/bubble/service/BubbleServiceImpl.java
- project/src/main/java/com/edison/project/domain/label/controller/LabelRestController.java
- project/src/main/java/com/edison/project/domain/label/dto/LabelRequestDTO.java
- project/src/main/java/com/edison/project/domain/label/service/LabelCommandService.java
- project/src/main/java/com/edison/project/domain/label/service/LabelCommandServiceImpl.java
- project/src/main/java/com/edison/project/domain/label/service/LabelQueryService.java
- project/src/main/java/com/edison/project/domain/label/service/LabelQueryServiceImpl.java
- project/src/main/java/com/edison/project/global/config/SecurityConfig.java
- project/src/main/java/com/edison/project/global/security/CustomUserPrincipal.java
- project/src/main/java/com/edison/project/global/security/JwtAuthenticationFilter.java
- project/src/main/java/com/edison/project/global/util/JwtUtil.java
- project/src/main/resources/application.properties
> close #36 
> 앞서 구현한 버블 목록 조회 이용해서 7일 내의 버블만 뽑아오는 API 추가로 구현하였습니다
> 아직 유저 인가 인증 부분 수정 전입니다 !! 관련 코드 머지되면 수정할게용
> ✨[FEAT] #36: 7일 이내 버블 목록 조회(나의 에디슨)

- project/src/main/java/com/edison/project/domain/bubble/controller/BubbleRestController.java
- project/src/main/java/com/edison/project/domain/bubble/dto/BubbleResponseDto.java
- project/src/main/java/com/edison/project/domain/bubble/repository/BubbleRepository.java
- project/src/main/java/com/edison/project/domain/bubble/service/BubbleService.java
- project/src/main/java/com/edison/project/domain/bubble/service/BubbleServiceImpl.java
> ex) close #43 
> (휴지통에서)삭제된 버블 목록을 조회하는 API입니다! 
- 토큰 없을 때
> ✨ [FEAT] #43 삭제된 버블 목록 조회(30일 이내)

- .github/workflows/dev_deploy.yml
- project/build.gradle
> 👷🏻‍♀️ ci: GitHub Actions 설정, build.gradle 수정

- .github/workflows/dev_deploy.yml
> 🐛 [BUG] deploy.yml 경로 수정

- .github/workflows/dev_deploy.yml
> 🐛 [BUG] deploy.yml - gradlew 경로 수정

- .github/workflows/dev_deploy.yml
> 🐛 [BUG] gradlew 관련 경로 수정

- project/src/main/java/com/edison/project/global/security/CustomAuthenticationEntryPoint.java
- merge 브랜치 확인할 것. **main으로 보내면 안 됨 :x:**
- PR 제목: `깃모지 [태그] #{이슈 번호}: {내용}`
- 예: ✨[FEAT] #20: 로그인 기능 구현
`close #{이슈 번호}`을 사용하면 PR이 merge되면 해당 이슈가 자동으로 닫힙니다.
> ex) #이슈번호, #이슈번호
>
> chore: customauthentication 파일 로그 추가

- .github/workflows/dev_deploy.yml
- project/src/main/java/com/edison/project/domain/artletter/controller/ArtletterController.java
- project/src/main/java/com/edison/project/domain/artletter/service/ArtletterServiceImpl.java
- project/src/main/java/com/edison/project/domain/member/controller/MemberRestController.java
- project/src/main/java/com/edison/project/domain/member/service/MemberService.java
- project/src/main/java/com/edison/project/domain/member/service/MemberServiceImpl.java
- project/src/main/java/com/edison/project/global/config/SecurityConfig.java
- project/src/main/java/com/edison/project/global/security/JwtAuthenticationFilter.java
> ex) #130 
> deploy.yml수정하였습니다!
>
> ❕ [!HOTFIX] #129 아트보드 접근, accessToken재발급 수정

- project/src/main/java/com/edison/project/common/status/ErrorStatus.java
- project/src/main/java/com/edison/project/domain/artletter/controller/ArtletterController.java
- project/src/main/java/com/edison/project/domain/artletter/dto/ArtletterDTO.java
- project/src/main/java/com/edison/project/domain/artletter/entity/Artletter.java
- project/src/main/java/com/edison/project/domain/artletter/service/ArtletterServiceImpl.java
> ex) #154 
- 썸네일 무조건 들어가야 한다고 하셔서 관련한 에러처리와 엔티티 수정 조금 했습니다!
> 🛠️ [REFACTOR] #154 : 아트레터 썸네일 not null로 오류 반환하도록 수정, close #154

- project/src/main/java/com/edison/project/domain/bubble/repository/BubbleRepository.java
- project/src/main/java/com/edison/project/domain/bubble/service/BubbleServiceImpl.java
- project/src/main/java/com/edison/project/domain/label/dto/LabelResponseDTO.java
- project/src/main/java/com/edison/project/domain/label/service/LabelQueryServiceImpl.java
> #160 
> 라벨 조회 api 응답에 createdAt, updatedAt 추가했습니다.
>
> ❕ [!HOTFIX] #160 전체(휴지통포함으로) 버블 조회 api 수정

- project/src/main/java/com/edison/project/domain/bubble/repository/BubbleRepository.java
- project/src/main/java/com/edison/project/domain/bubble/service/BubbleServiceImpl.java
- project/src/main/java/com/edison/project/domain/label/dto/LabelResponseDTO.java
- project/src/main/java/com/edison/project/domain/label/service/LabelQueryServiceImpl.java
- project/src/main/java/com/edison/project/domain/space/dto/SpaceResponseDto.java
> ❕ [!HOTFIX] #160 스페이스 버블 localIdx반환하도록 수정

- project/src/main/java/com/edison/project/domain/member/controller/MemberRestController.java
- project/src/main/java/com/edison/project/domain/member/dto/MemberResponseDto.java
- project/src/main/java/com/edison/project/domain/member/repository/MemberKeywordRepository.java
- project/src/main/java/com/edison/project/domain/member/service/MemberService.java
- project/src/main/java/com/edison/project/domain/member/service/MemberServiceImpl.java
- project/src/main/java/com/edison/project/domain/space/controller/SpaceController.java
- project/src/main/java/com/edison/project/domain/space/service/SpaceService.java
- project/src/main/java/com/edison/project/domain/space/service/SpaceServiceImpl.java
> ex) #96 
- 사용자 아이덴티티 키워드 가져와서 스트링 한줄로 반환하는 함수
- set 이용해서 중복값 response로 반환하지 않도록 수정
- system role, user role 추가하여 문맥 이어가지 않도록 수정 + 프롬프팅
- 아이덴티티 키워드 카테고리 별로 프롬프팅
> 봐주셨으면 하는 것!
- 중복값 없이 잘 반환되는지 확인해주세요
> ✨ [FEAT] #96: 페르소나 맞춤형 AI 프롬프팅, close #96

- project/src/main/java/com/edison/project/domain/keywords/controller/KeywordsRestController.java
- project/src/main/java/com/edison/project/domain/member/repository/MemberRepository.java
- project/src/main/java/com/edison/project/domain/member/service/MemberServiceImpl.java
> close #166 
> 기능적인 변화는 없고 중복되는 검증 코드를 제거했습니다~
위 API들 확인해주세요~!
> 🛠️ [REFACTOR] #166 아이덴티티 키워드 API QA

- project/src/main/java/com/edison/project/domain/artletter/service/ArtletterServiceImpl.java
- project/src/main/java/com/edison/project/domain/bubble/repository/BubbleRepository.java
- project/src/main/java/com/edison/project/domain/space/repository/SpaceRepository.java
- project/src/main/java/com/edison/project/domain/space/service/SpaceServiceImpl.java
> ex) #174
isTrashed 된것까지 가져와져서 전반적인 로직 손봤습니당
- 기존 데이터 가져와서 merge하는 것이 아닌.. 전체 돌리기
>
> ❕ [HOTFIX] #174 아트레터 검색, 조회 api 로그인 없을 때 에러 수정, close #174

- project/src/main/java/com/edison/project/domain/bubble/entity/BubbleBacklink.java
- project/src/main/java/com/edison/project/domain/bubble/repository/BubbleBacklinkRepository.java
- project/src/main/java/com/edison/project/domain/bubble/service/BubbleServiceImpl.java
> close #176 
> 백링크에 있는 버블을 삭제 시 백링크엔티티 삭제하도록 수정하였습니다.
>
> ❕ [HOTFIX]  #176 : 버블 백링크 삭제 수정

- .github/workflows/dev_deploy.yml
- project/src/main/java/com/edison/project/domain/bubble/entity/BubbleBacklink.java
- project/src/main/java/com/edison/project/domain/bubble/repository/BubbleBacklinkRepository.java
- project/src/main/java/com/edison/project/domain/bubble/service/BubbleServiceImpl.java
> [HOTFIX] RDS 관련 오류 수정 closes 188, Hotfix/188

- project/src/test/java/com/edison/project/ProjectApplicationTests.java
> [HOTFIX] test단의 mockbean 제거

- project/src/test/resources/application-test.properties
- merge 브랜치 확인할 것. **main으로 보내면 안 됨 :x:**
- PR 제목: `깃모지 [태그] #{이슈 번호}: {내용}`
- 예: ✨[FEAT] #20: 로그인 기능 구현
`close #{이슈 번호}`을 사용하면 PR이 merge되면 해당 이슈가 자동으로 닫힙니다.
> ex) #이슈번호, #이슈번호
>
> [HOTFIX] application-test.properties 추가

- project/src/main/java/com/edison/project/domain/bubble/controller/BubbleRestController.java
- project/src/main/java/com/edison/project/domain/bubble/dto/BubbleRequestDto.java
- project/src/main/java/com/edison/project/domain/bubble/dto/BubbleResponseDto.java
- project/src/main/java/com/edison/project/domain/bubble/entity/Bubble.java
- project/src/main/java/com/edison/project/domain/bubble/repository/BubbleRepository.java
- project/src/main/java/com/edison/project/domain/bubble/service/BubbleService.java
- project/src/main/java/com/edison/project/domain/bubble/service/BubbleServiceImpl.java
- project/src/main/java/com/edison/project/domain/label/controller/LabelRestController.java
- project/src/main/java/com/edison/project/domain/label/dto/LabelRequestDTO.java
- project/src/main/java/com/edison/project/domain/label/dto/LabelResponseDTO.java
- project/src/main/java/com/edison/project/domain/label/entity/Label.java
- project/src/main/java/com/edison/project/domain/label/repository/LabelRepository.java
- project/src/main/java/com/edison/project/domain/label/service/LabelQueryService.java
- project/src/main/java/com/edison/project/domain/label/service/LabelQueryServiceImpl.java
- project/src/main/java/com/edison/project/domain/space/dto/SpaceResponseDto.java
- project/src/main/java/com/edison/project/domain/space/repository/SpaceRepository.java
> ex) #193
bubble, label sync + space 관련하여 String으로 수정하였고, deleted_at = null 인것까지 검증하도록 수정하였습니다.
>
> [REFACTOR] 버블, 라벨 localIdx String으로 변경. closing #193, Refactor/193

- project/src/main/java/com/edison/project/domain/artletter/service/ArtletterServiceImpl.java
- project/src/main/java/com/edison/project/domain/space/controller/SpaceController.java
- project/src/main/java/com/edison/project/domain/space/entity/Space.java
- project/src/main/java/com/edison/project/domain/space/repository/SpaceRepository.java
- project/src/main/java/com/edison/project/domain/space/service/SpaceService.java
- project/src/main/java/com/edison/project/domain/space/service/SpaceServiceImpl.java
- project/src/main/java/com/edison/project/global/config/SecurityConfig.java
- project/src/main/resources/application.properties
> ex) #201
- GPT 요청 및 응답에서 bubble의 bubbleId 대신 localIdx 를 사용하도록 수정
- buildPromptWithLocalIdx() 함수 내 ID 포맷을 String(localIdx) 기반으로 전환
- GPT 응답 파싱 시에도 bubbleId가 아닌 localIdx로 Bubble을 매칭하도록 parseGptResponse() 리팩토링
- localIdx 기반 버블 매칭이 실패할 경우 로그 출력 및 해당 항목은 무시하도록 예외 처리
- 그 외 전체 변환, 선택 변환 API 모두 localIdx 기반 동작으로 통일
> [BUG] space localIdx로 반환하도록 오류 수정, closed #201

- nginx/nginx.conf
- merge 브랜치 확인할 것. **main으로 보내면 안 됨 :x:**
- PR 제목: `깃모지 [태그] #{이슈 번호}: {내용}`
- 예: ✨[FEAT] #20: 로그인 기능 구현
`close #{이슈 번호}`을 사용하면 PR이 merge되면 해당 이슈가 자동으로 닫힙니다.
> ex) #이슈번호, #이슈번호
>
> [BUG] ai 서버 관련 conf 파일 수정 및 route53 세팅 수정

- project/src/main/java/com/edison/project/domain/bubble/controller/BubbleRestController.java
- project/src/main/java/com/edison/project/domain/bubble/service/BubbleService.java
- project/src/main/java/com/edison/project/domain/bubble/service/BubbleServiceImpl.java
- project/src/main/java/com/edison/project/global/config/SecurityConfig.java
> close #211 
> 소프트 딜리트 된 버블을 포함하여 유저가 생성한 모든 버블을 조회하는 api입니다.
>
> ✨[FEAT] #211: 모든 버블(소프트 딜리트 포함) 조회 API 구현
